CC=g++
CFLAGS=-std=c++11 -O3 -I.
DEPS_HPP = circom.hpp calcwit.hpp fr.hpp
DEPS_O = main.o calcwit.o fr.o fr_asm.o

NASM=nasm -fmacho64 --prefix _

all: circuit

%.o: %.cpp $(DEPS_HPP)
	$(CC) -c $< $(CFLAGS)

fr_asm.o: fr.asm
	$(NASM) fr.asm -o fr_asm.o

circuit: $(DEPS_O) circuit.o
	$(CC) -o circuit *.o -lgmp -pthread
